### ISSUE TITLE
Quality comparison

### ISSUE THREAD

**Issue by druzhkov-paul** [TeCSAR-UNCC/EfficientHRNet#5]
In your paper you compare EfficientHRNets to other SOTA approaches in terms of quality/FLOPs/FPSes.
Could you please clarify a few points here:

- According to configs in this repository EfficientHRNets use flip augmentation at test time. That boost the quality, but at the cost of two passes of network over a single image. Do reported FLOPs numbers take this double pass into account? Please note, that quality numbers for Lightweight OpenPose seems to be evaluated without image flip, i.e. with a single pass over an image.
- Do FPS numbers take post-processing into account or only a forward pass (BTW, single or double?) of the network? Post-processing can have non-negligible cost and big impact on final quality at the same time. Also it might be not a good fit for software/hardware used for experiments. Lightweight OpenPose paper clearly states that it measures FPS for an end-to-end pipeline.
- Default evaluation protocol for that kind of networks uses input image blobs of different resolution (which depends on the aspect ratio of original image). I guess that FLOPs/FPS numbers are given for a fixed reference input resolution (like 384x384 for H0 model), am I right? At the same time variable input size is used during evaluation on MS COCO which kind of uncouples FLOPs/FPS numbers from AP numbers.

Thanks.

**Comment by ghost** [comment]
These are all really good questions and points. It highlights a lot of the difficulty we were having with constructing our comparisons. We decided to model our accuracy comparisons directly off of how HigherHRNet did theirs, since this was the state-of-the-art in the accuracy domain. This does include flip augmentation during testing and will give a slight boost in accuracy as compared to only performing a single pass. We also reported FLOPs in the same manner, which uses only a single pass as would be done in inference. Likewise we use single scale for inference with fixed image input sizes.

The FPS numbers we collected were for network inference only for the networks we tested. We actually attempted to reimplement a version of Lightweight OpenPose to test on the Xavier so that we could compare all the networks on the same device in the same way. But the results we were getting, even only measuring inference of the network, were worse than what they reported using OpenVINO, so we ultimately decided to use what they reported in their paper. I understand that this is not the most optimal comparison, comparing across different devices and with their result reported on an end-to-end pipeline. Lightweight OpenPose is an impressive network for real-time inference, and we had to include it in our comparisons. So we tried to include it in the best way we could with the results that they themselves reported.

I hope that clarifies our approach to our results for you. Please feel free to ask if you have any other questions, or if I wasn't clear enough.
