### ISSUE TITLE
Usage of bottleneck

### ISSUE THREAD

**Issue by devshree07** [TeCSAR-UNCC/EfficientHRNet#6]
In the model file 'pose_higher_hrnet.py', the bottleneck module has been commented and not used. But in models.py (present in config folder), it shows that all stages have been assigned the bottleneck block. How is that so? Can you explain it to me?

Thank you in advance.

**Comment by anerisheth19** [comment]
Please note that EfficientHRNet uses EfficientNet as the backbone and 'Basic' ResNet blocks for the HighResolutionModule stages. Please refer to Example Configs in order to see what blocks and configurations have been used. 'models.py' is specifically for the implementation of HigherHRNet repository linked in our README and has nothing to do with EfficientHRNet.

**Comment by devshree07** [comment]
Thank you so much for the clarification!
